### ISSUE TITLE
serde_yaml can't be used with serde-transcode

### ISSUE THREAD

**Issue by Mingun** [dtolnay/serde-yaml#123] opened 2018-12-31 13:03 UTC
`serde-transcode` requires instance of `Serializer`/`Deserializer`, but in `serde_yaml` they is private...

**Comment by Mingun** [comment] 2018-12-31 13:17
However, nevertheless it is possible, but it is unusual. Just instead of
```rust
let deserializer = ...;
let serializer   = ...;
serde_transcode::transcode(deserializer, serializer).expect("Transcode failed");
```
it is necessary to use
```rust
let deserializer = ...;
let tc = serde_transcode::Transcoder::new(deserializer);
serde_yaml::to_writer(io::stdout(), &tc).expect("Transcode failed");
```
It would be quite good to bring to have an opportunity to write everything in the one standard

**Comment by dtolnay** [comment] 2018-12-31 17:36
Thanks! Exposing the Serializer and Deserializer type are tracked in #44. Closing as a duplicate of that issue.

**Closed by dtolnay** 2018-12-31 17:36 UTC
