### ISSUE TITLE
allow yes/no as boolean values

### ISSUE THREAD

**Issue by wookietreiber** [dtolnay/serde-yaml#384] opened 2023-07-28 15:56 UTC
works:

```
foo: [true|false]
```

doesn't work:

```
foo: [yes|no]
```

```
... invalid type: string "yes", expected a boolean at line ...
... invalid type: string "no", expected a boolean at line ...
```

are you open to support `yes` and `no` for boolean values? I'd be open to provide a PR if it's not too difficult to implement. 

---

bit of background: I've been doing lots of work with Ansible, which allows `yes` and `no`. with Ansible, I'm even encouraging it by disallowing `true` and `false` with `yamllint` because it usually feels/reads more natural when reading/writing Ansible code.

**Comment by dtolnay** [comment] 2023-07-28 15:59
This is a duplicate of #379.

**Closed by dtolnay** 2023-07-28 15:59 UTC
